authorization_page:
  path: /
  controller: App\Controller\AuthorizationController::authorizationTemplate

registration_page:
  path: /registration
  controller: App\Controller\RegistrationController::registrationTemplate